# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YieldPridict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
            ],
        ),
    ]
