# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-13 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YieldPridict', '0002_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
